//! Compiles the ruleset *into* the guest image.
//!
//! Spec §5.2: "Rules are compiled into the guest image. No host-supplied
//! ruleset: a host-selected subset could omit the rule that denies a prompt,
//! making any proof unsound relative to the advertised policy."
//!
//! So this build script reads `policy/v1/{rules.json,manifest.json}` from the
//! repository, validates them against `policy-core`'s own types, and emits into
//! `OUT_DIR`:
//!
//! * `prepared_rules.postcard` — `PreparedRules` (the ruleset with every phrase
//!   already normalized), postcard-encoded. `include_bytes!` puts it in the ELF.
//! * `policy_consts.rs` — `POLICY_ID_V2` and `RULES_DIGEST`, as `&str` consts.
//!
//! Both outputs derive from the two JSON files, and `cargo:rerun-if-changed`
//! names both files, so **a one-byte rules change changes the ImageID**. That is
//! the §14 demo beat and it is a property of this file: if the rules ever get
//! loaded at runtime instead, the beat and the soundness argument go with it.
//!
//! Note the ordering that makes it work in both directions. `PreparedRules` is a
//! derived form, so in principle two different `rules.json` files could prepare
//! to the same bytes (a whitespace-only edit, say). `POLICY_ID_V2` is a hash of
//! the *raw* bytes and is baked in as a string const, so any byte-level change
//! changes the compiled image regardless.

use std::env;
use std::fs;
use std::path::PathBuf;

use policy_core::{policy_id, PolicyRules, PreparedRules};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // prover/methods/guest -> prover/methods -> prover -> repo root
    let policy_dir = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("policy")
        .join("v1");
    let rules_path = policy_dir.join("rules.json");
    let manifest_path = policy_dir.join("manifest.json");

    println!("cargo:rerun-if-changed={}", rules_path.display());
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let rules_bytes = fs::read(&rules_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", rules_path.display()));
    let manifest_json = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", manifest_path.display()));

    let rules_json = std::str::from_utf8(&rules_bytes)
        .unwrap_or_else(|e| panic!("{} is not UTF-8: {e}", rules_path.display()));
    // Validation, not just parsing: `PolicyRules` rejects a fractional weight,
    // a missing field, or a category map that would not round-trip in order.
    let rules = PolicyRules::from_json_str(rules_json)
        .unwrap_or_else(|e| panic!("{} is not a valid ruleset: {e}", rules_path.display()));

    let prepared = PreparedRules::prepare(&rules);
    let blob = postcard::to_allocvec(&prepared).expect("prepared rules serialize");

    let (policy_id_v2, rules_digest) = policy_id::policy_identity(&manifest_json, &rules_bytes)
        .unwrap_or_else(|e| panic!("cannot derive the policy identity: {e}"));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("prepared_rules.postcard"), &blob).expect("writing prepared rules");
    fs::write(
        out_dir.join("policy_consts.rs"),
        format!(
            "// Generated by prover/methods/guest/build.rs from\n\
             // policy/v1/manifest.json + policy/v1/rules.json. Do not edit.\n\
             \n\
             /// \"0x\" + hex(sha256(canonical_manifest_bytes || rules_bytes)).\n\
             /// Committed to the journal on every run.\n\
             const POLICY_ID_V2: &str = {policy_id_v2:?};\n\
             \n\
             /// \"0x\" + hex(sha256(rules_bytes)).\n\
             ///\n\
             /// The guest reads this exactly once, through a\n\
             /// `core::hint::black_box` in `main`, and that read is the whole\n\
             /// point: an unreferenced `const &str` is not emitted into the\n\
             /// binary at all, so the digest would not be in the measured image\n\
             /// and an auditor running `strings` over the ELF would not find\n\
             /// it. With the barrier it is in `.rodata`, checkable without\n\
             /// trusting a build log, and it is a second reason a one-byte\n\
             /// rules edit moves the ImageID.\n\
             const RULES_DIGEST: &str = {rules_digest:?};\n"
        ),
    )
    .expect("writing policy consts");
}
