use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // `cargo clippy` exports RUSTC_WORKSPACE_WRAPPER=clippy-driver. risc0-build
    // spawns a nested `cargo build` for the guest and sanitises `CARGO*` and
    // `RUSTUP_TOOLCHAIN` from that child's environment, but not the wrapper
    // variables — so the guest gets compiled by clippy-driver against
    // `riscv32im-risc0-zkvm-elf`, which has no clippy-visible `std`, and the
    // build dies with "can't find crate for `std`".
    //
    // Clearing them here keeps `cargo clippy -- -D warnings` working on the
    // workspace as documented in prover/README.md. The host is still linted; the
    // guest is compiled with its own toolchain, as it is in a plain build, and is
    // linted separately (`cargo clippy` inside prover/methods/guest — that crate
    // is its own workspace and the workspace lint never reached it).
    std::env::remove_var("RUSTC_WORKSPACE_WRAPPER");
    std::env::remove_var("RUSTC_WRAPPER");

    // The guest bakes the ruleset in (see methods/guest/build.rs), so a change to
    // either policy file must rebuild the image. Cargo will not infer that from
    // here: risc0-build's `rerun-if-changed` output covers the guest's *sources*,
    // and without these two lines a `rules.json` edit would leave a stale ELF —
    // and therefore a stale ImageID — sitting in target/.
    let policy_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("policy")
        .join("v1");
    let rules_path = policy_dir.join("rules.json");
    let manifest_path = policy_dir.join("manifest.json");
    println!("cargo:rerun-if-changed={}", rules_path.display());
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    // The same two identities the guest bakes in, re-derived here so host code
    // (tests today, `/health` and release.json in Tasks 5/6) can name them
    // without reading the policy directory at runtime. They are computed from
    // the same files by the same function; `prover/host/tests/guest_io.rs`
    // asserts the journal's policyId equals `methods::POLICY_ID_V2`, which is
    // what would catch the two ever disagreeing.
    let rules_bytes = fs::read(&rules_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", rules_path.display()));
    let manifest_json = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", manifest_path.display()));
    let (policy_id_v2, rules_digest) =
        policy_core::policy_id::policy_identity(&manifest_json, &rules_bytes)
            .unwrap_or_else(|e| panic!("cannot derive the policy identity: {e}"));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(
        out_dir.join("policy_consts.rs"),
        format!(
            "/// \"0x\" + hex(sha256(canonical_manifest_bytes || rules_bytes)) over\n\
             /// policy/v1/{{manifest,rules}}.json — the value baked into the guest image\n\
             /// and committed to every journal. Generated by prover/methods/build.rs.\n\
             pub const POLICY_ID_V2: &str = {policy_id_v2:?};\n\
             \n\
             /// \"0x\" + hex(sha256(rules_bytes)). Generated by prover/methods/build.rs.\n\
             pub const RULES_DIGEST: &str = {rules_digest:?};\n"
        ),
    )
    .expect("writing policy consts");

    risc0_build::embed_methods();
}
