//! The toolchain pins that `--emit-release` writes into `prover/release.json`.
//!
//! An ImageID is a hash of a *compiled* image, so "the same source" is not
//! enough to reproduce it: the compiler is an input. Three carry-forwards from
//! Tasks 1-3 say so explicitly, and this file is the answer to all three:
//!
//! * Task 1: `rust-toolchain.toml` floated on `stable` while the README pinned
//!   1.97.1. The channel is now pinned (see that file) and the exact `rustc`
//!   that built *this* binary is recorded here rather than asserted in prose.
//! * Task 2: `str::to_lowercase` is a third Unicode table source, and it lives
//!   in the toolchain's `core`, not in a crate anyone can pin in `Cargo.toml`.
//!   The toolchain that matters for that is the **guest** one — the image is
//!   what evaluates policy — so the rzup Rust toolchain is recorded too, read
//!   through the same `rzup` call `risc0-build` itself makes
//!   (`risc0-build-3.0.6/src/lib.rs:373-383`) so the two cannot drift.
//! * Task 3: `unicode-normalization` and `unicode-properties` are the other two
//!   Unicode sources; their exact resolved versions come out of `Cargo.lock`,
//!   not out of the `^`-ranged requirement in a manifest.
//!
//! Everything here is read at *build* time and baked into the binary as a
//! `&'static str`. Nothing is read from the environment at run time, so
//! `--emit-release` describes the build it came out of and cannot be talked into
//! describing a different one.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let lock_path = manifest_dir.join("..").join("Cargo.lock");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", lock_path.display());

    // The compiler cargo is driving. `RUSTC` is set by cargo for every build
    // script; falling back to the PATH `rustc` would be a different compiler
    // than the one compiling this crate, which is the whole thing being pinned.
    let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_owned());
    let host_rustc = version_of(&rustc);

    // The guest's compiler, located exactly the way `risc0-build` locates it:
    // rzup's default Rust toolchain, whose `bin/rustc` is forced into the nested
    // guest build through the `RUSTC` environment variable. `rustc --version` on
    // that path gives the commit hash as well as the release number.
    let (guest_toolchain_version, guest_rustc) = match rzup::Rzup::new()
        .and_then(|r| r.get_default_version(&rzup::Component::RustToolchain))
    {
        Ok(Some((version, path))) => (
            version.to_string(),
            version_of(&path.join("bin").join("rustc").to_string_lossy()),
        ),
        // Not a build failure: `methods` will have panicked long before this
        // crate compiles if the toolchain is genuinely missing. Recording the
        // absence is more useful than guessing a version.
        Ok(None) => ("unavailable".to_owned(), "unavailable".to_owned()),
        Err(e) => {
            println!("cargo:warning=rzup lookup failed: {e}");
            ("unavailable".to_owned(), "unavailable".to_owned())
        }
    };

    let lock = std::fs::read_to_string(&lock_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lock_path.display()));

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("toolchain.rs");
    let body = format!(
        "// Generated by prover/host/build.rs. Do not edit.\n\
         pub const HOST_RUSTC: &str = {host_rustc:?};\n\
         pub const GUEST_RUSTC: &str = {guest_rustc:?};\n\
         pub const RZUP_RUST_TOOLCHAIN: &str = {guest_toolchain_version:?};\n\
         pub const RISC0_BUILD_CRATE: &str = {risc0_build:?};\n\
         pub const UNICODE_NORMALIZATION_CRATE: &str = {unicode_normalization:?};\n\
         pub const UNICODE_PROPERTIES_CRATE: &str = {unicode_properties:?};\n",
        risc0_build = locked_version(&lock, "risc0-build"),
        unicode_normalization = locked_version(&lock, "unicode-normalization"),
        unicode_properties = locked_version(&lock, "unicode-properties"),
    );
    write_if_changed(&out, &body);
}

/// `<tool> --version` with the leading tool name stripped: `rustc 1.97.1
/// (8bab26f4f 2026-07-14)` becomes `1.97.1 (8bab26f4f 2026-07-14)`.
fn version_of(rustc: &str) -> String {
    let output = match Command::new(rustc).arg("--version").output() {
        Ok(o) if o.status.success() => o,
        _ => return "unavailable".to_owned(),
    };
    let line = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    line.strip_prefix("rustc ").unwrap_or(&line).to_owned()
}

/// The resolved version of `name` in `Cargo.lock`.
///
/// Hand-rolled rather than a `toml` build-dependency: the shape being read is
/// three lines of a generated file, and a parser dependency here is one more
/// thing that has to be pinned to pin anything. A missing crate is a panic —
/// silently writing `"unknown"` into a manifest whose entire job is to be
/// precise would be worse than not building.
fn locked_version(lock: &str, name: &str) -> String {
    let needle = format!("name = \"{name}\"");
    let mut versions: Vec<String> = Vec::new();
    let mut lines = lock.lines();
    while let Some(line) = lines.next() {
        if line.trim() != needle {
            continue;
        }
        let version = lines
            .next()
            .and_then(|l| l.trim().strip_prefix("version = \""))
            .and_then(|l| l.strip_suffix('"'))
            .unwrap_or_else(|| panic!("no version line after {needle} in Cargo.lock"));
        versions.push(version.to_owned());
    }
    match versions.len() {
        1 => versions.pop().expect("checked length"),
        // Two copies of a Unicode-table crate in one graph is exactly the
        // situation a pin is supposed to make visible, so say so rather than
        // picking one.
        0 => panic!("{name} is not in Cargo.lock"),
        _ => panic!(
            "{name} appears {} times in Cargo.lock: {versions:?}",
            versions.len()
        ),
    }
}

/// Avoid rewriting an unchanged file: a touched `OUT_DIR` file makes cargo
/// consider dependents dirty on the next build.
fn write_if_changed(path: &Path, body: &str) {
    if std::fs::read_to_string(path).ok().as_deref() == Some(body) {
        return;
    }
    std::fs::write(path, body).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
}
